version: '3.8'

services:
  api:
    build:
      context: ./Geoportal.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=geoportal_db;Username=rodarter;Password=viperr_password
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: rodarter
      POSTGRES_PASSWORD: viperr_password
      POSTGRES_DB: geoportal_db
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"