name: app
description: "Geoportal Uzbekistan - Mobile Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
    uses-material-design: true
  generate: true # Добавь эту строку
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  device_info_plus: ^12.3.0
  google_fonts: ^8.0.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Пакет для автоматической генерации иконок приложения
  flutter_launcher_icons: ^0.13.1

# Конфигурация иконок (заменится во всем проекте одной командой)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png